library(tidyverse)

ugan.labels <- ugan %>% 
  mutate(
    gender = factor(gender, labels = c("Male", "Female"), levels = 1:2),
    marital = factor(marital, labels = c("Single (never married)",
                                         "Living with partner",
                                         "Married",
                                         "Civil partnership",
                                         "Separated",
                                         "Divorced",
                                         "Widowed",
                                         "Prefer not to say"),
                     levels = 1:8),
    child_dependants = case_when(child_dependants == 6 ~ 0, T ~ child_dependants),
    healthtype_2 = factor(healthtype_2, levels = 1:2, labels = c("Public", "Private")),
    healthtype = factor(healthtype, levels = 1:12, labels = c("Medical unit",
                                                              "surgical",
                                                              "intensive care",
                                                              "paediatric",
                                                              "emergency",
                                                              "infectious disease ward",
                                                              "isolation ward",
                                                              "maternity",
                                                              "Ambulance",
                                                              "Laboratory",
                                                              "Palliative Care",
                                                              "Other")),
    role = factor(role, labels = c("Consultant",
                                   "Medical doctor",
                                   "Dentist",
                                   "Intern doctor",
                                   "Midwife",
                                   "Nurse",
                                   "Allied health professional",
                                   "Social worker/counsellor",
                                   "Administrative",
                                   "Other"),
                  levels = 1:10),
  If_Yes = factor(If_Yes, labels = c("daily",
                                     "more than one day per week",
                                     "less than one day per week",
                                     "rarely",
                                     "no patient contact",
                                     "don't know"),
                  levels = 1:6),
  jobrole = factor(jobrole, labels = c("Fulltime",
                                       "part time",
                                       "casual or locum staff",
                                       "retired",
                                       "student",
                                       "other"),
                   levels = 1:6),
  across(experience_1 :experience_4, ~factor(., levels = 1:3, labels = c("Yes", "No", "Unsure"))),
  across(c(service_demand_1 : emotion_5, trust_1:trust_3), ~factor(., labels = c("strongly disagree",
                                                "disagree",
                                                "somewhat disagree",
                                                "neither agree nor disagree",
                                                "somewhat agree",
                                                "agree",
                                                "strongly agree"),
                                  levels = 1:7))
  ) 

write.csv(ugan.labels, "data for merging-20211221T110041Z-001/data for merging/uganda needed vars labelled.csv")
    